### ISSUE TITLE
axios is undefined

### ISSUE THREAD

**Issue by leishaoxiong** [nmxiaowei/avue#506]
将lib文件单独引入项目，然后启动项目后，浏览器报axios is undefined

**Comment by nmxiaowei** [comment]
描述详细点。加截图



---Original---
From: ***@***.***&gt;
Date: Wed, Sep 15, 2021 15:47 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [nmxiaowei/avue] axios is undefined (#506)




 
将lib文件单独引入项目，然后启动项目后，浏览器报axios is undefined
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by leishaoxiong** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月15日(星期三) 下午3:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [nmxiaowei/avue] axios is undefined (#506)





 描述详细点。加截图 
 
 
 
 ---Original--- 
 From: ***@***.***&amp;gt; 
 Date: Wed, Sep 15, 2021 15:47 PM 
 To: ***@***.***&amp;gt;; 
 Cc: ***@***.***&amp;gt;; 
 Subject: [nmxiaowei/avue] axios is undefined (#506) 
 
 
 
 
   
 将lib文件单独引入项目，然后启动项目后，浏览器报axios is undefined 
   
 — 
 You are receiving this because you are subscribed to this thread. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android. 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by nmxiaowei** [comment]
项目引入axios
