### ISSUE TITLE
表单下拉配置项res改不了

### ISSUE THREAD

**Issue by 793338483** [nmxiaowei/avue#513]
props的配置项res，默认就是res.data,接口返回res.rows，好嘛，改不了了，既然给出这么个配置项，能直接按用户输入的来？非得把res.data作为前置条件算啥

**Comment by nmxiaowei** [comment]
dicFormatter也可以配置




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nmxiaowei/avue"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月15日(星期一) 下午4:59
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[nmxiaowei/avue] 表单下拉配置项res改不了 (Issue #513)





 
props的配置项res，默认就是res.data,接口返回res.rows，好嘛，改不了了，既然给出这么个配置项，能直接按用户输入的来？非得把res.data作为前置条件算啥
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 793338483** [comment]
最开始就是用这个进行配置，没效后才用的res进行配置，2.8.22版本
